Calibrate:
  Transmission PeakNo: 1
  beta: 2
  peakNo: 1

PhotonEnergyProcessor:
  singleRun: False
  energyStart: 0
  energyStop: 30
  energyStep: 1


PeakFinder:
  reduction: "mean"
  symmetric: False
  threshold: 0.2
  peakNo: 1
  stackTrains: True
  stackPulses: True
  trainStackSize: null
  pulseStackStart: null
  pulseStackStop: null
  pulseStackSize: null
  smoothWindow: 5
 



FLASHLoader:
    #[0,2,5,6,7,8,10,11,12,14,15]
    #[0.0,null, 45.0,null,null, 112.5,135.0,157.5,180.0,null,225.0,247.5,270.0,null,315,337.5]
    ToF: [0,1,2,3,4,5,6,7,8,9,10,12,14,15]
    angles: [ 0.0,23.4,45.6,56.7,67.8,112.2,123.2,134.4,145.5,168.9,180.0,191.1,247.8,259.9,292.2,336.6]
    trainStart: 0
    trainStop: null
    trainStep: 1
    pulseStart: null
    pulseStop: null
    pulseStep: 1
    baselineRegion: [0,10]

DoocspieStream:
    baselineRegion: [0,10]
    addresses:
      0: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH00/CH00.DAQ.TD'
      1: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH01/CH00.DAQ.TD'
      2: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH02/CH00.DAQ.TD'
      3: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH03/CH00.DAQ.TD'
      4: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH04/CH00.DAQ.TD'
      5: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH05/CH00.DAQ.TD'
      6: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH06/CH00.DAQ.TD'
      7: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH07/CH00.DAQ.TD'
      8: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH08/CH00.DAQ.TD'
      9: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH09/CH00.DAQ.TD'
      10: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH10/CH00.DAQ.TD'
      11: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH11/CH00.DAQ.TD'
      12: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH12/CH00.DAQ.TD'
      13: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH13/CH00.DAQ.TD'
      14: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH14/CH00.DAQ.TD'
      15: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH15/CH00.DAQ.TD'
    angles:
      0: 0.0
      1: 23.4
      2: 45.6
      3: 56.7
      4: 67.8
      5: 112.2
      6: 123.2
      7: 134.4
      8: 145.5
      9: 168.9
      10: 180.0
      11: 191.1
      12: 247.8
      13: 259.9
      14: 292.2
      15: 336.6


NXSLoader:
    ToF:    [0, 1, 2,3,4, 5, 6,7, 8, 9, 10,11, 12,13,14] # [0,1,2,5,6,8,9,10,12,13,14] [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
    angles: [0.0,22.5,45.0,67.5,90.0,112.5,135.0,157.5,180.0,202.5,225.0,247.5,270.0,292.5,315.0,337.5]
          # [0.0,22.5,45.0,67.5,90.0,112.5,135.0,157.5,180.0,202.5,225.0,247.5,270.0,292.5,315.0]
    sampleShift:
      0: 0
      1: 4
      2: -11
      3: 41
      4: 6
      5: 1
      6: -9
      7: 44
      8: 11
      9: 8
      10: -4
      11: 49
      12: 8
      13: 21
      14: -1
    filePattern: "*_{run_number:05d}.nxs"
    baselineRegion: [0,10]
    trainStart: null
    trainStop: null
