Calibrate:
  Transmission PeakNo: 1
  beta: 0.21297526881720433
  peakNo: 1

PhotonEnergyProcessor:
  singleRun: False
  energyStart: 0
  energyStop: 30
  energyStep: 1


PeakFinder:
  reduction: "mean"
  symmetric: False
  threshold: 0.2
  peakNo: 1
  stackTrains: True
  stackPulses: True
  trainStackSize: null
  pulseStackStart: null
  pulseStackStop: null
  pulseStackSize: null
  smoothWindow: 5
 



FLASHLoader:
    #[0,2,5,6,7,8,10,11,12,14,15]
    #[0.0,null, 45.0,null,null, 112.5,135.0,157.5,180.0,null,225.0,247.5,270.0,null,315,337.5]
    ToF: [0,1,2,3,4,5,6,7,8,9,10,12,14,15]
    angles: [ 0.0,23.4,45.6,56.7,67.8,112.2,123.2,134.4,145.5,168.9,180.0,191.1,247.8,259.9,292.2,336.6]
    trainStart: 0
    trainStop: null
    trainStep: 1
    pulseStart: null
    pulseStop: null
    pulseStep: 1
    baselineRegion: [0,10]

DoocspieStream:
    addresses:
      0: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH00'
      1: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH01'
      2: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH02'
      3: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH03'
      4: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH04'
      5: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH05'
      6: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH06'
      7: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH07'
      8: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH08'
      9: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH09'
      10: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH10'
      11: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH11'
      12: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH12'
      13: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH13'
      14: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH14'
      15: 'FLASH.FEL/ADC.ADQ/GHZADC1.CH15'

NXSLoader:
    ToF:    [0, 1, 2,3,4, 5, 6,7, 8, 9, 10,11, 12,13,14] # [0,1,2,5,6,8,9,10,12,13,14] [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
    angles: [0.0,22.5,45.0,67.5,90.0,112.5,135.0,157.5,180.0,202.5,225.0,247.5,270.0,292.5,315.0,337.5]
          # [0.0,22.5,45.0,67.5,90.0,112.5,135.0,157.5,180.0,202.5,225.0,247.5,270.0,292.5,315.0]
    sampleShift:
      0: 0
      1: 4
      2: -11
      3: 41
      4: 6
      5: 1
      6: -9
      7: 44
      8: 11
      9: 8
      10: -4
      11: 49
      12: 8
      13: 21
      14: -1
    filePattern: "*_{run_number:05d}.nxs"
    baselineRegion: [0,10]
    trainStart: null
    trainStop: null
